// ============================================================
// ZeParty Admin Portal — World Currencies & Country ISO Mapping
// Comprehensive Country-to-Currency Directory
// ============================================================

export const WORLD_CURRENCIES = [
  { code: 'USD', name: 'US Dollar ($)', symbol: '$', defaultCountry: 'US' },
  { code: 'EUR', name: 'Euro (€)', symbol: '€', defaultCountry: 'EU' },
  { code: 'GBP', name: 'British Pound (£)', symbol: '£', defaultCountry: 'GB' },
  { code: 'PKR', name: 'Pakistani Rupee (₨)', symbol: '₨', defaultCountry: 'PK' },
  { code: 'SAR', name: 'Saudi Riyal (﷼)', symbol: '﷼', defaultCountry: 'SA' },
  { code: 'AED', name: 'UAE Dirham (د.إ)', symbol: 'د.إ', defaultCountry: 'AE' },
  { code: 'TRY', name: 'Turkish Lira (₺)', symbol: '₺', defaultCountry: 'TR' },
  { code: 'BRL', name: 'Brazilian Real (R$)', symbol: 'R$', defaultCountry: 'BR' },
  { code: 'INR', name: 'Indian Rupee (₹)', symbol: '₹', defaultCountry: 'IN' },
  { code: 'CAD', name: 'Canadian Dollar (C$)', symbol: 'C$', defaultCountry: 'CA' },
  { code: 'AUD', name: 'Australian Dollar (A$)', symbol: 'A$', defaultCountry: 'AU' },
  { code: 'JPY', name: 'Japanese Yen (¥)', symbol: '¥', defaultCountry: 'JP' },
  { code: 'CNY', name: 'Chinese Yuan (¥)', symbol: '¥', defaultCountry: 'CN' },
  { code: 'KWD', name: 'Kuwaiti Dinar (KD)', symbol: 'KD', defaultCountry: 'KW' },
  { code: 'QAR', name: 'Qatari Riyal (QR)', symbol: 'QR', defaultCountry: 'QA' },
  { code: 'OMR', name: 'Omani Rial (RO)', symbol: 'RO', defaultCountry: 'OM' },
  { code: 'BHD', name: 'Bahraini Dinar (BD)', symbol: 'BD', defaultCountry: 'BH' },
  { code: 'EGP', name: 'Egyptian Pound (E£)', symbol: 'E£', defaultCountry: 'EG' },
  { code: 'IDR', name: 'Indonesian Rupiah (Rp)', symbol: 'Rp', defaultCountry: 'ID' },
  { code: 'PHP', name: 'Philippine Peso (₱)', symbol: '₱', defaultCountry: 'PH' },
  { code: 'MYR', name: 'Malaysian Ringgit (RM)', symbol: 'RM', defaultCountry: 'MY' },
  { code: 'THB', name: 'Thai Baht (฿)', symbol: '฿', defaultCountry: 'TH' },
  { code: 'VND', name: 'Vietnamese Dong (₫)', symbol: '₫', defaultCountry: 'VN' },
  { code: 'KRW', name: 'South Korean Won (₩)', symbol: '₩', defaultCountry: 'KR' },
  { code: 'SGD', name: 'Singapore Dollar (S$)', symbol: 'S$', defaultCountry: 'SG' },
  { code: 'NZD', name: 'New Zealand Dollar (NZ$)', symbol: 'NZ$', defaultCountry: 'NZ' },
  { code: 'CHF', name: 'Swiss Franc (CHF)', symbol: 'CHF', defaultCountry: 'CH' },
  { code: 'ZAR', name: 'South African Rand (R)', symbol: 'R', defaultCountry: 'ZA' },
  { code: 'NGN', name: 'Nigerian Naira (₦)', symbol: '₦', defaultCountry: 'NG' },
  { code: 'KES', name: 'Kenyan Shilling (KSh)', symbol: 'KSh', defaultCountry: 'KE' },
  { code: 'GHS', name: 'Ghanaian Cedi (GH₵)', symbol: 'GH₵', defaultCountry: 'GH' },
  { code: 'BDT', name: 'Bangladeshi Taka (৳)', symbol: '৳', defaultCountry: 'BD' },
  { code: 'MXN', name: 'Mexican Peso (Mex$)', symbol: 'Mex$', defaultCountry: 'MX' },
  { code: 'ARS', name: 'Argentine Peso ($)', symbol: '$', defaultCountry: 'AR' },
  { code: 'COP', name: 'Colombian Peso ($)', symbol: '$', defaultCountry: 'CO' },
  { code: 'CLP', name: 'Chilean Peso ($)', symbol: '$', defaultCountry: 'CL' },
  { code: 'PEN', name: 'Peruvian Sol (S/)', symbol: 'S/', defaultCountry: 'PE' },
  { code: 'RUB', name: 'Russian Ruble (₽)', symbol: '₽', defaultCountry: 'RU' },
  { code: 'IQD', name: 'Iraqi Dinar (IQD)', symbol: 'IQD', defaultCountry: 'IQ' },
  { code: 'JOD', name: 'Jordanian Dinar (JOD)', symbol: 'JOD', defaultCountry: 'JO' },
  { code: 'LBP', name: 'Lebanese Pound (L£)', symbol: 'L£', defaultCountry: 'LB' },
  { code: 'MAD', name: 'Moroccan Dirham (MAD)', symbol: 'MAD', defaultCountry: 'MA' },
  { code: 'DZD', name: 'Algerian Dinar (DZD)', symbol: 'DZD', defaultCountry: 'DZ' },
  { code: 'TND', name: 'Tunisian Dinar (TND)', symbol: 'TND', defaultCountry: 'TN' },
  { code: 'AZN', name: 'Azerbaijani Manat (₼)', symbol: '₼', defaultCountry: 'AZ' },
  { code: 'KZT', name: 'Kazakhstani Tenge (₸)', symbol: '₸', defaultCountry: 'KZ' },
  { code: 'UZS', name: 'Uzbekistani Som (UZS)', symbol: 'UZS', defaultCountry: 'UZ' }
];

export const COUNTRY_TO_CURRENCY = {
  US: 'USD',
  GLOBAL: 'USD',
  ALL: 'USD',
  EU: 'EUR',
  GB: 'GBP',
  PK: 'PKR',
  SA: 'SAR',
  AE: 'AED',
  TR: 'TRY',
  BR: 'BRL',
  IN: 'INR',
  CA: 'CAD',
  AU: 'AUD',
  JP: 'JPY',
  CN: 'CNY',
  KW: 'KWD',
  QA: 'QAR',
  OM: 'OMR',
  BH: 'BHD',
  EG: 'EGP',
  ID: 'IDR',
  PH: 'PHP',
  MY: 'MYR',
  TH: 'THB',
  VN: 'VND',
  KR: 'KRW',
  SG: 'SGD',
  NZ: 'NZD',
  CH: 'CHF',
  ZA: 'ZAR',
  NG: 'NGN',
  KE: 'KES',
  GH: 'GHS',
  BD: 'BDT',
  MX: 'MXN',
  AR: 'ARS',
  CO: 'COP',
  CL: 'CLP',
  PE: 'PEN',
  RU: 'RUB',
  IQ: 'IQD',
  JO: 'JOD',
  LB: 'LBP',
  MA: 'MAD',
  DZ: 'DZD',
  TN: 'TND',
  AZ: 'AZN',
  KZ: 'KZT',
  UZ: 'UZS',
  DE: 'EUR',
  FR: 'EUR',
  IT: 'EUR',
  ES: 'EUR',
  NL: 'EUR',
  BE: 'EUR',
  AT: 'EUR',
  PT: 'EUR',
  GR: 'EUR',
  IE: 'EUR',
  FI: 'EUR'
};

export function getCurrencyForCountry(countryCode) {
  if (!countryCode) return 'USD';
  const upper = countryCode.toUpperCase().trim();
  return COUNTRY_TO_CURRENCY[upper] || 'USD';
}

export default {
  WORLD_CURRENCIES,
  COUNTRY_TO_CURRENCY,
  getCurrencyForCountry
};
