import prisma from '../src/config/database.js';

export const canonicalStoreItems = [
  // ─── CARS / MOUNTS (VEHICLE) ───
  {
    id: 'car_phantom',
    name: 'Phantom Hypercar',
    assetType: 'VEHICLE',
    assetSubcategory: 'ANIMATED_SVGA',
    thumbnailUrl: 'assets/animations/mystery_entry.webp',
    animationFileUrl: 'assets/animations/mystery_entry.webp',
    priceCoins: 500000n,
    validDays: 30,
    roomAvailability: 'BOTH',
    isVipExclusive: false,
    isActive: true,
  },
  {
    id: 'car_astral',
    name: 'Astral Dragon Mount',
    assetType: 'VEHICLE',
    assetSubcategory: 'ANIMATED_SVGA',
    thumbnailUrl: 'assets/nobles/emperor_entrance.png',
    animationFileUrl: 'assets/nobles/emperor_entrance.png',
    priceCoins: 350000n,
    validDays: 30,
    roomAvailability: 'BOTH',
    isVipExclusive: false,
    isActive: true,
  },
  {
    id: 'car_royal',
    name: 'Royal Chariot',
    assetType: 'VEHICLE',
    assetSubcategory: 'ANIMATED_SVGA',
    thumbnailUrl: 'assets/nobles/marquis_entrance.png',
    animationFileUrl: 'assets/nobles/marquis_entrance.png',
    priceCoins: 200000n,
    validDays: 30,
    roomAvailability: 'BOTH',
    isVipExclusive: false,
    isActive: true,
  },
  {
    id: 'car_cyber_jet',
    name: 'Cyber Hoverjet',
    assetType: 'VEHICLE',
    assetSubcategory: 'ANIMATED_SVGA',
    thumbnailUrl: 'assets/svip/svip12_entry.png',
    animationFileUrl: 'assets/svip/svip12_entry.png',
    priceCoins: 150000n,
    validDays: 30,
    roomAvailability: 'BOTH',
    isVipExclusive: false,
    isActive: true,
  },
  {
    id: 'car_gold_cruiser',
    name: 'Gold Cruiser',
    assetType: 'VEHICLE',
    assetSubcategory: 'STATIC',
    thumbnailUrl: 'assets/svip/svip8_entry.png',
    animationFileUrl: 'assets/svip/svip8_entry.png',
    priceCoins: 80000n,
    validDays: 30,
    roomAvailability: 'BOTH',
    isVipExclusive: false,
    isActive: true,
  },
  {
    id: 'car_neon_coupe',
    name: 'Neon Coupe',
    assetType: 'VEHICLE',
    assetSubcategory: 'STATIC',
    thumbnailUrl: 'assets/svip/svip6_entry.png',
    animationFileUrl: 'assets/svip/svip6_entry.png',
    priceCoins: 45000n,
    validDays: 30,
    roomAvailability: 'BOTH',
    isVipExclusive: false,
    isActive: true,
  },
  {
    id: 'ast-car-01',
    name: 'Golden Sports Car',
    assetType: 'VEHICLE',
    assetSubcategory: 'ANIMATED_SVGA',
    thumbnailUrl: 'https://cdn.zeparty.app/assets/cars/car_gold.png',
    animationFileUrl: 'https://cdn.zeparty.app/svga/car_gold.svga',
    priceCoins: 500000n,
    validDays: 30,
    roomAvailability: 'BOTH',
    isVipExclusive: true,
    minVipLevelRequired: 3,
    isActive: true,
  },
  {
    id: 'ast-car-02',
    name: 'Luxury SUV',
    assetType: 'VEHICLE',
    assetSubcategory: 'STATIC',
    thumbnailUrl: 'https://cdn.zeparty.app/assets/cars/suv_black.png',
    priceCoins: 400000n,
    validDays: 30,
    roomAvailability: 'BOTH',
    isVipExclusive: false,
    isActive: true,
  },

  // ─── AVATAR FRAMES (FRAME) ───
  {
    id: 'frame_zp134',
    name: 'Golden Glory Frame',
    assetType: 'FRAME',
    assetSubcategory: 'STATIC',
    thumbnailUrl: 'assets/store/ZP-134_avatar-frames_frame.webp',
    staticFileUrl: 'assets/store/ZP-134_avatar-frames_frame.webp',
    priceCoins: 250000n,
    validDays: 30,
    roomAvailability: 'BOTH',
    isActive: true,
  },
  {
    id: 'frame_zp135',
    name: 'Starlight Crown Frame',
    assetType: 'FRAME',
    assetSubcategory: 'STATIC',
    thumbnailUrl: 'assets/store/ZP-135_avatar-frames_frame.webp',
    staticFileUrl: 'assets/store/ZP-135_avatar-frames_frame.webp',
    priceCoins: 180000n,
    validDays: 30,
    roomAvailability: 'BOTH',
    isActive: true,
  },
  {
    id: 'frame_zp136',
    name: 'Cyber Neon Frame',
    assetType: 'FRAME',
    assetSubcategory: 'STATIC',
    thumbnailUrl: 'assets/store/ZP-136_avatar-frames_frame.webp',
    staticFileUrl: 'assets/store/ZP-136_avatar-frames_frame.webp',
    priceCoins: 120000n,
    validDays: 30,
    roomAvailability: 'BOTH',
    isActive: true,
  },
  {
    id: 'frame_zp137',
    name: 'Celestial Aura Frame',
    assetType: 'FRAME',
    assetSubcategory: 'STATIC',
    thumbnailUrl: 'assets/store/ZP-137_avatar-frames_frame.webp',
    staticFileUrl: 'assets/store/ZP-137_avatar-frames_frame.webp',
    priceCoins: 90000n,
    validDays: 30,
    roomAvailability: 'BOTH',
    isActive: true,
  },
  {
    id: 'frame_zp138',
    name: 'Luxe Diamond Frame',
    assetType: 'FRAME',
    assetSubcategory: 'STATIC',
    thumbnailUrl: 'assets/store/ZP-138_avatar-frames_frame.webp',
    staticFileUrl: 'assets/store/ZP-138_avatar-frames_frame.webp',
    priceCoins: 60000n,
    validDays: 30,
    roomAvailability: 'BOTH',
    isActive: true,
  },
  {
    id: 'frame_zp139',
    name: 'Mystic Wings Frame',
    assetType: 'FRAME',
    assetSubcategory: 'STATIC',
    thumbnailUrl: 'assets/store/ZP-139_avatar-frames_frame.webp',
    staticFileUrl: 'assets/store/ZP-139_avatar-frames_frame.webp',
    priceCoins: 40000n,
    validDays: 30,
    roomAvailability: 'BOTH',
    isActive: true,
  },
  {
    id: 'frame_zp140',
    name: 'Solar Flare Frame',
    assetType: 'FRAME',
    assetSubcategory: 'STATIC',
    thumbnailUrl: 'assets/store/ZP-140_avatar-frames_frame.webp',
    staticFileUrl: 'assets/store/ZP-140_avatar-frames_frame.webp',
    priceCoins: 25000n,
    validDays: 30,
    roomAvailability: 'BOTH',
    isActive: true,
  },
  {
    id: 'frame_zp141',
    name: 'Vortex Shield Frame',
    assetType: 'FRAME',
    assetSubcategory: 'STATIC',
    thumbnailUrl: 'assets/store/ZP-141_avatar-frames_frame.webp',
    staticFileUrl: 'assets/store/ZP-141_avatar-frames_frame.webp',
    priceCoins: 300000n,
    validDays: 30,
    roomAvailability: 'BOTH',
    isActive: true,
  },
  {
    id: 'frame_zp142',
    name: 'Astral Ring Frame',
    assetType: 'FRAME',
    assetSubcategory: 'STATIC',
    thumbnailUrl: 'assets/store/ZP-142_avatar-frames_frame.webp',
    staticFileUrl: 'assets/store/ZP-142_avatar-frames_frame.webp',
    priceCoins: 200000n,
    validDays: 30,
    roomAvailability: 'BOTH',
    isActive: true,
  },
  {
    id: 'frame_zp143',
    name: 'Phantom Elite Frame',
    assetType: 'FRAME',
    assetSubcategory: 'STATIC',
    thumbnailUrl: 'assets/store/ZP-143_avatar-frames_frame.webp',
    staticFileUrl: 'assets/store/ZP-143_avatar-frames_frame.webp',
    priceCoins: 100000n,
    validDays: 30,
    roomAvailability: 'BOTH',
    isActive: true,
  },
  {
    id: 'ast-frame-01',
    name: 'Golden Warrior Frame',
    assetType: 'FRAME',
    assetSubcategory: 'STATIC',
    thumbnailUrl: 'https://cdn.zeparty.app/assets/frames/warrior.png',
    priceCoins: 300000n,
    validDays: 15,
    roomAvailability: 'BOTH',
    isActive: true,
  },
  {
    id: 'ast-frame-02',
    name: 'Spider Hero Frame',
    assetType: 'FRAME',
    assetSubcategory: 'STATIC',
    thumbnailUrl: 'https://cdn.zeparty.app/assets/frames/spider.png',
    priceCoins: 400000n,
    validDays: 15,
    roomAvailability: 'BOTH',
    isActive: true,
  },

  // ─── SPECIAL CARDS (BADGE) ───
  {
    id: 'card_zp165',
    name: 'Golden Supreme Card',
    assetType: 'BADGE',
    assetSubcategory: 'STATIC',
    thumbnailUrl: 'assets/store/ZP-165_special-cards_card.webp',
    staticFileUrl: 'assets/store/ZP-165_special-cards_card.webp',
    priceCoins: 250000n,
    validDays: 30,
    roomAvailability: 'BOTH',
    isActive: true,
  },
  {
    id: 'card_zp166',
    name: 'Starlight Royalty Card',
    assetType: 'BADGE',
    assetSubcategory: 'STATIC',
    thumbnailUrl: 'assets/store/ZP-166_special-cards_card.webp',
    staticFileUrl: 'assets/store/ZP-166_special-cards_card.webp',
    priceCoins: 180000n,
    validDays: 30,
    roomAvailability: 'BOTH',
    isActive: true,
  },
  {
    id: 'card_zp167',
    name: 'Luxe Gold Card',
    assetType: 'BADGE',
    assetSubcategory: 'STATIC',
    thumbnailUrl: 'assets/store/ZP-167_special-cards_card.webp',
    staticFileUrl: 'assets/store/ZP-167_special-cards_card.webp',
    priceCoins: 60000n,
    validDays: 30,
    roomAvailability: 'BOTH',
    isActive: true,
  },
  {
    id: 'card_zp168',
    name: 'Cyber Platinum Card',
    assetType: 'BADGE',
    assetSubcategory: 'STATIC',
    thumbnailUrl: 'assets/store/ZP-168_special-cards_card.webp',
    staticFileUrl: 'assets/store/ZP-168_special-cards_card.webp',
    priceCoins: 100000n,
    validDays: 30,
    roomAvailability: 'BOTH',
    isActive: true,
  },
  {
    id: 'card_zp169',
    name: 'Ruby Elite Card',
    assetType: 'BADGE',
    assetSubcategory: 'STATIC',
    thumbnailUrl: 'assets/store/ZP-169_special-cards_card.webp',
    staticFileUrl: 'assets/store/ZP-169_special-cards_card.webp',
    priceCoins: 50000n,
    validDays: 30,
    roomAvailability: 'BOTH',
    isActive: true,
  },
  {
    id: 'card_zp170',
    name: 'Sapphire Glow Card',
    assetType: 'BADGE',
    assetSubcategory: 'STATIC',
    thumbnailUrl: 'assets/store/ZP-170_special-cards_card.webp',
    staticFileUrl: 'assets/store/ZP-170_special-cards_card.webp',
    priceCoins: 20000n,
    validDays: 30,
    roomAvailability: 'BOTH',
    isActive: true,
  },

  // ─── CHAT BUBBLES (CHAT_BUBBLE) ───
  {
    id: 'bubble_zp144',
    name: 'Golden Royal Bubble',
    assetType: 'CHAT_BUBBLE',
    assetSubcategory: 'STATIC',
    thumbnailUrl: 'assets/store/ZP-144_chat-bubbles_bubble.webp',
    staticFileUrl: 'assets/store/ZP-144_chat-bubbles_bubble.webp',
    priceCoins: 150000n,
    validDays: 30,
    roomAvailability: 'BOTH',
    isActive: true,
  },
  {
    id: 'bubble_zp145',
    name: 'Purple Luxe Bubble',
    assetType: 'CHAT_BUBBLE',
    assetSubcategory: 'STATIC',
    thumbnailUrl: 'assets/store/ZP-145_chat-bubbles_bubble.webp',
    staticFileUrl: 'assets/store/ZP-145_chat-bubbles_bubble.webp',
    priceCoins: 90000n,
    validDays: 30,
    roomAvailability: 'BOTH',
    isActive: true,
  },
  {
    id: 'bubble_zp146',
    name: 'Crimson Flame Bubble',
    assetType: 'CHAT_BUBBLE',
    assetSubcategory: 'STATIC',
    thumbnailUrl: 'assets/store/ZP-146_chat-bubbles_bubble.webp',
    staticFileUrl: 'assets/store/ZP-146_chat-bubbles_bubble.webp',
    priceCoins: 70000n,
    validDays: 30,
    roomAvailability: 'BOTH',
    isActive: true,
  },
  {
    id: 'bubble_zp147',
    name: 'Royal Blue Bubble',
    assetType: 'CHAT_BUBBLE',
    assetSubcategory: 'STATIC',
    thumbnailUrl: 'assets/store/ZP-147_chat-bubbles_bubble.webp',
    staticFileUrl: 'assets/store/ZP-147_chat-bubbles_bubble.webp',
    priceCoins: 45000n,
    validDays: 30,
    roomAvailability: 'BOTH',
    isActive: true,
  },
  {
    id: 'bubble_zp148',
    name: 'Sparkle Gold Bubble',
    assetType: 'CHAT_BUBBLE',
    assetSubcategory: 'STATIC',
    thumbnailUrl: 'assets/store/ZP-148_chat-bubbles_bubble.webp',
    staticFileUrl: 'assets/store/ZP-148_chat-bubbles_bubble.webp',
    priceCoins: 200000n,
    validDays: 30,
    roomAvailability: 'BOTH',
    isActive: true,
  },
  {
    id: 'bubble_zp149',
    name: 'Violet Cyber Bubble',
    assetType: 'CHAT_BUBBLE',
    assetSubcategory: 'STATIC',
    thumbnailUrl: 'assets/store/ZP-149_chat-bubbles_bubble.webp',
    staticFileUrl: 'assets/store/ZP-149_chat-bubbles_bubble.webp',
    priceCoins: 110000n,
    validDays: 30,
    roomAvailability: 'BOTH',
    isActive: true,
  },
  {
    id: 'bubble_zp150',
    name: 'Amber Glow Bubble',
    assetType: 'CHAT_BUBBLE',
    assetSubcategory: 'STATIC',
    thumbnailUrl: 'assets/store/ZP-150_chat-bubbles_bubble.webp',
    staticFileUrl: 'assets/store/ZP-150_chat-bubbles_bubble.webp',
    priceCoins: 60000n,
    validDays: 30,
    roomAvailability: 'BOTH',
    isActive: true,
  },
  {
    id: 'bubble_zp151',
    name: 'Magic Neon Bubble',
    assetType: 'CHAT_BUBBLE',
    assetSubcategory: 'STATIC',
    thumbnailUrl: 'assets/store/ZP-151_chat-bubbles_bubble.webp',
    staticFileUrl: 'assets/store/ZP-151_chat-bubbles_bubble.webp',
    priceCoins: 35000n,
    validDays: 30,
    roomAvailability: 'BOTH',
    isActive: true,
  },
  {
    id: 'bubble_zp152',
    name: 'Crystal Wave Bubble',
    assetType: 'CHAT_BUBBLE',
    assetSubcategory: 'STATIC',
    thumbnailUrl: 'assets/store/ZP-152_chat-bubbles_bubble.webp',
    staticFileUrl: 'assets/store/ZP-152_chat-bubbles_bubble.webp',
    priceCoins: 40000n,
    validDays: 30,
    roomAvailability: 'BOTH',
    isActive: true,
  },
  {
    id: 'bubble_zp153',
    name: 'Emerald Shine Bubble',
    assetType: 'CHAT_BUBBLE',
    assetSubcategory: 'STATIC',
    thumbnailUrl: 'assets/store/ZP-153_chat-bubbles_bubble.webp',
    staticFileUrl: 'assets/store/ZP-153_chat-bubbles_bubble.webp',
    priceCoins: 45000n,
    validDays: 30,
    roomAvailability: 'BOTH',
    isActive: true,
  },
  {
    id: 'bubble_zp154',
    name: 'Solar Flare Bubble',
    assetType: 'CHAT_BUBBLE',
    assetSubcategory: 'STATIC',
    thumbnailUrl: 'assets/store/ZP-154_chat-bubbles_bubble.webp',
    staticFileUrl: 'assets/store/ZP-154_chat-bubbles_bubble.webp',
    priceCoins: 50000n,
    validDays: 30,
    roomAvailability: 'BOTH',
    isActive: true,
  },
  {
    id: 'bubble_zp155',
    name: 'Ocean Blue Bubble',
    assetType: 'CHAT_BUBBLE',
    assetSubcategory: 'STATIC',
    thumbnailUrl: 'assets/store/ZP-155_chat-bubbles_bubble.webp',
    staticFileUrl: 'assets/store/ZP-155_chat-bubbles_bubble.webp',
    priceCoins: 55000n,
    validDays: 30,
    roomAvailability: 'BOTH',
    isActive: true,
  },
  {
    id: 'bubble_zp156',
    name: 'Galaxy Dust Bubble',
    assetType: 'CHAT_BUBBLE',
    assetSubcategory: 'STATIC',
    thumbnailUrl: 'assets/store/ZP-156_chat-bubbles_bubble.webp',
    staticFileUrl: 'assets/store/ZP-156_chat-bubbles_bubble.webp',
    priceCoins: 60000n,
    validDays: 30,
    roomAvailability: 'BOTH',
    isActive: true,
  },
  {
    id: 'bubble_zp157',
    name: 'Pink Petal Bubble',
    assetType: 'CHAT_BUBBLE',
    assetSubcategory: 'STATIC',
    thumbnailUrl: 'assets/store/ZP-157_chat-bubbles_bubble.webp',
    staticFileUrl: 'assets/store/ZP-157_chat-bubbles_bubble.webp',
    priceCoins: 30000n,
    validDays: 30,
    roomAvailability: 'BOTH',
    isActive: true,
  },
  {
    id: 'bubble_zp158',
    name: 'Aurora Light Bubble',
    assetType: 'CHAT_BUBBLE',
    assetSubcategory: 'STATIC',
    thumbnailUrl: 'assets/store/ZP-158_chat-bubbles_bubble.webp',
    staticFileUrl: 'assets/store/ZP-158_chat-bubbles_bubble.webp',
    priceCoins: 35000n,
    validDays: 30,
    roomAvailability: 'BOTH',
    isActive: true,
  },
  {
    id: 'ast-bubble-01',
    name: 'Unicorn Dream Bubble',
    assetType: 'CHAT_BUBBLE',
    assetSubcategory: 'STATIC',
    thumbnailUrl: 'https://cdn.zeparty.app/assets/bubbles/unicorn.png',
    priceCoins: 250000n,
    validDays: 30,
    roomAvailability: 'BOTH',
    isActive: true,
  },

  // ─── ROOM BACKGROUNDS (ENTRY_EFFECT) ───
  {
    id: 'bg_zp159',
    name: 'Imperial Palace Realm',
    assetType: 'ENTRY_EFFECT',
    assetSubcategory: 'STATIC',
    thumbnailUrl: 'assets/store/ZP-159_room-backgrounds_background.webp',
    staticFileUrl: 'assets/store/ZP-159_room-backgrounds_background.webp',
    priceCoins: 300000n,
    validDays: 30,
    roomAvailability: 'BOTH',
    isActive: true,
  },
  {
    id: 'bg_zp160',
    name: 'Starlight Castle Theme',
    assetType: 'ENTRY_EFFECT',
    assetSubcategory: 'STATIC',
    thumbnailUrl: 'assets/store/ZP-160_room-backgrounds_background.webp',
    staticFileUrl: 'assets/store/ZP-160_room-backgrounds_background.webp',
    priceCoins: 120000n,
    validDays: 30,
    roomAvailability: 'BOTH',
    isActive: true,
  },
  {
    id: 'bg_zp161',
    name: 'Luxe Manor Theme',
    assetType: 'ENTRY_EFFECT',
    assetSubcategory: 'STATIC',
    thumbnailUrl: 'assets/store/ZP-161_room-backgrounds_background.webp',
    staticFileUrl: 'assets/store/ZP-161_room-backgrounds_background.webp',
    priceCoins: 75000n,
    validDays: 30,
    roomAvailability: 'BOTH',
    isActive: true,
  },
  {
    id: 'bg_zp162',
    name: 'Cyber Stage Realm',
    assetType: 'ENTRY_EFFECT',
    assetSubcategory: 'STATIC',
    thumbnailUrl: 'assets/store/ZP-162_room-backgrounds_background.webp',
    staticFileUrl: 'assets/store/ZP-162_room-backgrounds_background.webp',
    priceCoins: 180000n,
    validDays: 30,
    roomAvailability: 'BOTH',
    isActive: true,
  },
  {
    id: 'bg_zp163',
    name: 'Neon Glow Realm',
    assetType: 'ENTRY_EFFECT',
    assetSubcategory: 'STATIC',
    thumbnailUrl: 'assets/store/ZP-163_room-backgrounds_background.webp',
    staticFileUrl: 'assets/store/ZP-163_room-backgrounds_background.webp',
    priceCoins: 100000n,
    validDays: 30,
    roomAvailability: 'BOTH',
    isActive: true,
  },
  {
    id: 'bg_zp164',
    name: 'Ruby Lounge Theme',
    assetType: 'ENTRY_EFFECT',
    assetSubcategory: 'STATIC',
    thumbnailUrl: 'assets/store/ZP-164_room-backgrounds_background.webp',
    staticFileUrl: 'assets/store/ZP-164_room-backgrounds_background.webp',
    priceCoins: 65000n,
    validDays: 30,
    roomAvailability: 'BOTH',
    isActive: true,
  },

  // ─── ROLE & SVIP BADGES (BADGE) ───
  {
    id: 'badge_role_admin',
    name: 'Admin Role Badge',
    assetType: 'BADGE',
    assetSubcategory: 'STATIC',
    thumbnailUrl: 'assets/roles/ZP-178_admin_badge.webp',
    priceCoins: 100000n,
    validDays: 30,
    roomAvailability: 'BOTH',
    isActive: true,
  },
  {
    id: 'badge_role_agency',
    name: 'Agency Master Badge',
    assetType: 'BADGE',
    assetSubcategory: 'STATIC',
    thumbnailUrl: 'assets/roles/ZP-181_agency_badge.webp',
    priceCoins: 80000n,
    validDays: 30,
    roomAvailability: 'BOTH',
    isActive: true,
  },
  {
    id: 'badge_role_assistant',
    name: 'Assistant Officer Badge',
    assetType: 'BADGE',
    assetSubcategory: 'STATIC',
    thumbnailUrl: 'assets/roles/ZP-184_assistant_badge.webp',
    priceCoins: 60000n,
    validDays: 30,
    roomAvailability: 'BOTH',
    isActive: true,
  },
  {
    id: 'badge_role_bd',
    name: 'BD Director Badge',
    assetType: 'BADGE',
    assetSubcategory: 'STATIC',
    thumbnailUrl: 'assets/roles/ZP-187_bd_badge.webp',
    priceCoins: 120000n,
    validDays: 30,
    roomAvailability: 'BOTH',
    isActive: true,
  },
  {
    id: 'badge_role_boss',
    name: 'Grand Boss Badge',
    assetType: 'BADGE',
    assetSubcategory: 'STATIC',
    thumbnailUrl: 'assets/roles/ZP-190_boss_badge.webp',
    priceCoins: 150000n,
    validDays: 30,
    roomAvailability: 'BOTH',
    isActive: true,
  },
  {
    id: 'badge_role_ceo',
    name: 'CEO Executive Badge',
    assetType: 'BADGE',
    assetSubcategory: 'STATIC',
    thumbnailUrl: 'assets/roles/ZP-193_ceo_badge.webp',
    priceCoins: 200000n,
    validDays: 30,
    roomAvailability: 'BOTH',
    isActive: true,
  },
  {
    id: 'badge_role_coins_seller',
    name: 'Coins Merchant Badge',
    assetType: 'BADGE',
    assetSubcategory: 'STATIC',
    thumbnailUrl: 'assets/roles/ZP-196_coins-saller_badge.webp',
    priceCoins: 75000n,
    validDays: 30,
    roomAvailability: 'BOTH',
    isActive: true,
  },
  {
    id: 'badge_role_cs',
    name: 'Customer Support Badge',
    assetType: 'BADGE',
    assetSubcategory: 'STATIC',
    thumbnailUrl: 'assets/roles/ZP-198_cs_badge.webp',
    priceCoins: 50000n,
    validDays: 30,
    roomAvailability: 'BOTH',
    isActive: true,
  },
  {
    id: 'badge_role_game_master',
    name: 'Game Master Badge',
    assetType: 'BADGE',
    assetSubcategory: 'STATIC',
    thumbnailUrl: 'assets/roles/ZP-201_game-master_badge.webp',
    priceCoins: 90000n,
    validDays: 30,
    roomAvailability: 'BOTH',
    isActive: true,
  },
  {
    id: 'badge_role_host',
    name: 'Star Host Badge',
    assetType: 'BADGE',
    assetSubcategory: 'STATIC',
    thumbnailUrl: 'assets/roles/ZP-204_host_badge.webp',
    priceCoins: 85000n,
    validDays: 30,
    roomAvailability: 'BOTH',
    isActive: true,
  },
  {
    id: 'badge_role_lover',
    name: 'Lover Romance Badge',
    assetType: 'BADGE',
    assetSubcategory: 'STATIC',
    thumbnailUrl: 'assets/roles/ZP-207_lover_badge.webp',
    priceCoins: 65000n,
    validDays: 30,
    roomAvailability: 'BOTH',
    isActive: true,
  },
  {
    id: 'badge_role_manager',
    name: 'General Manager Badge',
    assetType: 'BADGE',
    assetSubcategory: 'STATIC',
    thumbnailUrl: 'assets/roles/ZP-210_manager_badge.webp',
    priceCoins: 110000n,
    validDays: 30,
    roomAvailability: 'BOTH',
    isActive: true,
  },
  {
    id: 'badge_role_merchant',
    name: 'Official Merchant Badge',
    assetType: 'BADGE',
    assetSubcategory: 'STATIC',
    thumbnailUrl: 'assets/roles/ZP-212_marchent_badge.webp',
    priceCoins: 95000n,
    validDays: 30,
    roomAvailability: 'BOTH',
    isActive: true,
  },
  {
    id: 'badge_role_official',
    name: 'Official VIP Badge',
    assetType: 'BADGE',
    assetSubcategory: 'STATIC',
    thumbnailUrl: 'assets/roles/ZP-215_official_badge.webp',
    priceCoins: 130000n,
    validDays: 30,
    roomAvailability: 'BOTH',
    isActive: true,
  },
  {
    id: 'badge_role_super_admin',
    name: 'Super Admin Badge',
    assetType: 'BADGE',
    assetSubcategory: 'STATIC',
    thumbnailUrl: 'assets/roles/ZP-218_super-admin_badge.webp',
    priceCoins: 300000n,
    validDays: 30,
    roomAvailability: 'BOTH',
    isActive: true,
  },
  {
    id: 'badge_role_top_fan',
    name: 'Top Fan Elite Badge',
    assetType: 'BADGE',
    assetSubcategory: 'STATIC',
    thumbnailUrl: 'assets/roles/ZP-220_top-fan_badge.webp',
    priceCoins: 70000n,
    validDays: 30,
    roomAvailability: 'BOTH',
    isActive: true,
  },
  {
    id: 'badge_zp054',
    name: 'SVIP Star Badge',
    assetType: 'BADGE',
    assetSubcategory: 'STATIC',
    thumbnailUrl: 'assets/svip/ZP-054_svip-1_badge.webp',
    priceCoins: 50000n,
    validDays: 30,
    roomAvailability: 'BOTH',
    isActive: true,
  },
  {
    id: 'badge_zp056',
    name: 'Royalty Crown Badge',
    assetType: 'BADGE',
    assetSubcategory: 'STATIC',
    thumbnailUrl: 'assets/svip/ZP-056_svip-3_badge.webp',
    priceCoins: 90000n,
    validDays: 30,
    roomAvailability: 'BOTH',
    isActive: true,
  },
  {
    id: 'badge_zp065',
    name: 'Cyber Elite Badge',
    assetType: 'BADGE',
    assetSubcategory: 'STATIC',
    thumbnailUrl: 'assets/svip/ZP-065_svip-6_badge.webp',
    priceCoins: 150000n,
    validDays: 30,
    roomAvailability: 'BOTH',
    isActive: true,
  },
  {
    id: 'badge_zp079',
    name: 'Gold Phoenix Badge',
    assetType: 'BADGE',
    assetSubcategory: 'STATIC',
    thumbnailUrl: 'assets/svip/ZP-079_svip-8_badge.webp',
    priceCoins: 250000n,
    validDays: 30,
    roomAvailability: 'BOTH',
    isActive: true,
  },
  {
    id: 'badge_zp100',
    name: 'Imperial Dragon Badge',
    assetType: 'BADGE',
    assetSubcategory: 'STATIC',
    thumbnailUrl: 'assets/svip/ZP-100_svip-11_badge.webp',
    priceCoins: 400000n,
    validDays: 30,
    roomAvailability: 'BOTH',
    isActive: true,
  },
  {
    id: 'badge_zp127',
    name: 'Supreme Sovereign Badge',
    assetType: 'BADGE',
    assetSubcategory: 'STATIC',
    thumbnailUrl: 'assets/svip/ZP-127_svip-15_badge.webp',
    priceCoins: 600000n,
    validDays: 30,
    roomAvailability: 'BOTH',
    isActive: true,
  },
];

async function seed() {
  console.log('Seeding canonical store assets into PostgreSQL...');
  let count = 0;
  for (const item of canonicalStoreItems) {
    await prisma.asset.upsert({
      where: { id: item.id },
      update: {
        name: item.name,
        assetType: item.assetType,
        assetSubcategory: item.assetSubcategory,
        thumbnailUrl: item.thumbnailUrl,
        staticFileUrl: item.staticFileUrl || item.thumbnailUrl,
        animationFileUrl: item.animationFileUrl || null,
        priceCoins: item.priceCoins,
        validDays: item.validDays,
        roomAvailability: item.roomAvailability || 'BOTH',
        isVipExclusive: Boolean(item.isVipExclusive),
        minVipLevelRequired: item.minVipLevelRequired || 0,
        isActive: true,
      },
      create: {
        id: item.id,
        name: item.name,
        assetType: item.assetType,
        assetSubcategory: item.assetSubcategory,
        thumbnailUrl: item.thumbnailUrl,
        staticFileUrl: item.staticFileUrl || item.thumbnailUrl,
        animationFileUrl: item.animationFileUrl || null,
        priceCoins: item.priceCoins,
        validDays: item.validDays,
        roomAvailability: item.roomAvailability || 'BOTH',
        isVipExclusive: Boolean(item.isVipExclusive),
        minVipLevelRequired: item.minVipLevelRequired || 0,
        isActive: true,
      },
    });
    count++;
  }

  console.log(`Successfully upserted ${count} store assets into database.`);
  await prisma.$disconnect();
}

seed().catch((err) => {
  console.error('Seed error:', err);
  process.exit(1);
});
