// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAa5vFcXnjvvO2-_XPvyf787mB_noK3_nc',
    appId: '1:13274132785:web:590ed774e5b29937bc8010',
    messagingSenderId: '13274132785',
    projectId: 'zeparty-79828',
    authDomain: 'zeparty-79828.firebaseapp.com',
    storageBucket: 'zeparty-79828.firebasestorage.app',
    measurementId: 'G-N9LRNS8NWJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAZRAw83GcwurMrWhbdwmbn5xj7mXvywI',
    appId: '1:13274132785:android:30c7463ffbb7de93bc8010',
    messagingSenderId: '13274132785',
    projectId: 'zeparty-79828',
    storageBucket: 'zeparty-79828.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5zPmAzybbwSyfzKOI4ZFunQoHPjaAUsE',
    appId: '1:13274132785:ios:483e62c673cec610bc8010',
    messagingSenderId: '13274132785',
    projectId: 'zeparty-79828',
    storageBucket: 'zeparty-79828.firebasestorage.app',
    iosBundleId: 'com.example.liveStreamApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5zPmAzybbwSyfzKOI4ZFunQoHPjaAUsE',
    appId: '1:13274132785:ios:483e62c673cec610bc8010',
    messagingSenderId: '13274132785',
    projectId: 'zeparty-79828',
    storageBucket: 'zeparty-79828.firebasestorage.app',
    iosBundleId: 'com.example.liveStreamApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAa5vFcXnjvvO2-_XPvyf787mB_noK3_nc',
    appId: '1:13274132785:web:e643ec5406dbdb36bc8010',
    messagingSenderId: '13274132785',
    projectId: 'zeparty-79828',
    authDomain: 'zeparty-79828.firebaseapp.com',
    storageBucket: 'zeparty-79828.firebasestorage.app',
    measurementId: 'G-7BZX05G2X5',
  );
}
