platform :ios, '15.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  target 'RunnerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
    end
  end

  # Fix DT_TOOLCHAIN_DIR for Xcode 15+ / 16+
  installer.aggregate_targets.each do |target|
    target.xcconfigs.each do |config_name, config_file|
      config_file.attributes['LIBRARY_SEARCH_PATHS'] = config_file.attributes['LIBRARY_SEARCH_PATHS'].gsub('DT_TOOLCHAIN_DIR', 'TOOLCHAIN_DIR') if config_file.attributes['LIBRARY_SEARCH_PATHS']
      config_file.save_as(Pathname.new("#{target.xcconfig_path(config_name)}"))
    end
  end

  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if config.base_configuration_reference.is_a?(Xcodeproj::Project::Object::PBXFileReference)
        xcconfig_path = config.base_configuration_reference.real_path
        if File.exist?(xcconfig_path)
          build_settings = File.read(xcconfig_path)
          build_settings.gsub!(/DT_TOOLCHAIN_DIR/, 'TOOLCHAIN_DIR')
          File.open(xcconfig_path, "w") { |file| file << build_settings }
        end
      end
    end
  end
end
